api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        standard_put: true # Added for PropelTech
    # Added for PropelTech
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform'
    path_segment_name_generator: api_platform.metadata.path_segment_name_generator.dash
