App\Entity\Person:
    attributes:
        id:
            groups:
                - person_collection_get.read
                - person_collection_post.read
                - person_item_get.read
                - person_item_put.read
        firstName:
            serialized_name: first_name
            groups:
                - person_collection_get.read
                - person_collection_post.read
                - person_collection_post.write
                - person_item_get.read
                - person_item_put.read
                - person_item_put.write
        lastName:
            serialized_name: last_name
            groups:
                - person_collection_get.read
                - person_collection_post.read
                - person_collection_post.write
                - person_item_get.read
                - person_item_put.read
                - person_item_put.write
        phone:
            groups:
                - person_collection_get.read
                - person_collection_post.read
                - person_collection_post.write
                - person_item_get.read
                - person_item_put.read
                - person_item_put.write
        email:
            groups:
                - person_collection_get.read
                - person_collection_post.read
                - person_collection_post.write
                - person_item_get.read
                - person_item_put.read
                - person_item_put.write
